sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t kevincoakley/heron .

script:
    - docker run --name my_heron -d -p 127.0.0.1:8888:8888 -p 127.0.0.1:8889:8889 kevincoakley/heron
    - sleep 60
    - bash ./tests/test_port_8889.sh

after_script:
    - docker ps -a
    - docker logs my_heron
    - docker top my_heron
