---
- name: Download heron-client
  get_url:
    url: "https://github.com/twitter/heron/releases/download/{{ heron_version }}/heron-client-install-{{ heron_version }}-centos.sh"
    dest: "/tmp/heron-client-install-{{ heron_version }}-centos.sh"
    mode: 0755

- name: Download heron-tools
  get_url:
    url: "https://github.com/twitter/heron/releases/download/{{ heron_version }}/heron-tools-install-{{ heron_version }}-centos.sh"
    dest: "/tmp/heron-tools-install-{{ heron_version }}-centos.sh"
    mode: 0755

- name: Install heron client
  shell: "/tmp/heron-client-install-{{ heron_version }}-centos.sh"
  environment:
    JAVA_HOME: /usr/lib/jvm/java/
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

- name: Install heron tools
  shell: "/tmp/heron-tools-install-{{ heron_version }}-centos.sh"
  environment:
    JAVA_HOME: /usr/lib/jvm/java/
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
